<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSBzMZ1d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSBzMZ1d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSBzMZ1d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSBzMZ1d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSBzMZ1d\App_KernelDevDebugContainer([
    'container.build_hash' => 'SBzMZ1d',
    'container.build_id' => 'ae924241',
    'container.build_time' => 1697457449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSBzMZ1d');
