<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_author_show' => [['name'], ['_controller' => 'App\\Controller\\AuthorController::showAuthor'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/author/show']], [], [], []],
    'app_list' => [[], ['_controller' => 'App\\Controller\\AuthorController::list'], [], [['text', '/author/list']], [], [], []],
    'app_author_details' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::details'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author/details']], [], [], []],
    'app_author_read' => [[], ['_controller' => 'App\\Controller\\AuthorController::read'], [], [['text', '/author/read']], [], [], []],
    'app_author_add' => [[], ['_controller' => 'App\\Controller\\AuthorController::add'], [], [['text', '/author/add']], [], [], []],
    'delete_author' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author/delete']], [], [], []],
    'update_author' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author/update']], [], [], []],
    'app_homes' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/home']], [], [], []],
    'app_service_show' => [['name'], ['_controller' => 'App\\Controller\\ServiceController::showService'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/service/show']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
