<?php

namespace ContainerSBzMZ1d;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZOE_YWUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZOE.YWU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZOE.YWU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authorrep' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'authorrep' => 'App\\Repository\\AuthorRepository',
            'doctrine' => '?',
        ]);
    }
}
