<?php

namespace ContainerAsNAmn9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BMDOD1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bMDOD_1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bMDOD_1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthorController::add' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\AuthorController::delete' => ['privates', '.service_locator.2qW74oC', 'get_ServiceLocator_2qW74oCService', true],
            'App\\Controller\\AuthorController::read' => ['privates', '.service_locator.Vs5EBJv', 'get_ServiceLocator_Vs5EBJvService', true],
            'App\\Controller\\AuthorController::update' => ['privates', '.service_locator.ZOE.YWU', 'get_ServiceLocator_ZOE_YWUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AuthorController:add' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\AuthorController:delete' => ['privates', '.service_locator.2qW74oC', 'get_ServiceLocator_2qW74oCService', true],
            'App\\Controller\\AuthorController:read' => ['privates', '.service_locator.Vs5EBJv', 'get_ServiceLocator_Vs5EBJvService', true],
            'App\\Controller\\AuthorController:update' => ['privates', '.service_locator.ZOE.YWU', 'get_ServiceLocator_ZOE_YWUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AuthorController::add' => '?',
            'App\\Controller\\AuthorController::delete' => '?',
            'App\\Controller\\AuthorController::read' => '?',
            'App\\Controller\\AuthorController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthorController:add' => '?',
            'App\\Controller\\AuthorController:delete' => '?',
            'App\\Controller\\AuthorController:read' => '?',
            'App\\Controller\\AuthorController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
