<?php

namespace ContainerAsNAmn9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2qW74oCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2qW74oC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2qW74oC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.2qW74oC.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.2qW74oC": it references class "App\\Entity\\Author" but no such service exists.'],
        ], [
            'author' => 'App\\Entity\\Author',
        ]);
    }
}
